version : "3"
services:
  laraving:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laraving
    restart: always
    depends_on:
      - laraving-db
      - laraving-pma
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: 'Laraving'
      APP_ENV: 'local'
      APP_DEBUG: 'true'
      APP_URL: 'http://220.122.1.1'
      DB_CONNECTION: 'mysql'
    networks:
      laraving-network:
        ipv4_address: 220.122.1.1

  laraving-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: app
    entrypoint:
        sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS test_db;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        "
    container_name: laraving-db
    restart: always
    volumes:
      - laraving-db-disk:/var/lib/mysql
    networks:
      laraving-network:
        ipv4_address: 220.122.1.2

  laraving-pma:
    image: phpmyadmin:apache
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: laraving-db
    container_name: laraving-pma
    restart: always
    networks:
      laraving-network:
        ipv4_address: 220.122.1.3


# On-disk storage of DB data, when containers are stopped/removed
volumes:
  laraving-db-disk: {}

# Local network for services running using this docker-compose config
networks:
  laraving-network:
    ipam:
      driver: default
      config:
        - subnet: 220.122.0.0/16
