version : "3"
services:
  ironsell-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ironsell-website
    depends_on:
      - ironsell-website-db
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: 'ironsell website'
      APP_ENV: 'local'
      APP_DEBUG: 'true'
      APP_URL: 'http://220.117.1.1'
      DB_CONNECTION: 'mysql'
      DATABASE_URL: 'mysql://dbuser:dbpass@ironsell-website-db/main'
    networks:
      ironsell-website-network:
        ipv4_address: 220.117.1.1

  ironsell-website-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: main
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    container_name: ironsell-website-db
    volumes:
      - ironsell-website-db-disk:/var/lib/mysql
    networks:
      ironsell-website-network:
        ipv4_address: 220.117.1.2

  ironsell-website-pma:
    image: phpmyadmin:apache
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ironsell-website-db
    container_name: ironsell-website-pma
    networks:
      ironsell-website-network:
        ipv4_address: 220.117.1.3


# On-disk storage of DB data, when containers are stopped/removed
volumes:
  ironsell-website-db-disk: {}

# Local network for services running using this docker-compose config
networks:
  ironsell-website-network:
    ipam:
      driver: default
      config:
        - subnet: 220.117.0.0/16
